name: yuya
description: "Test your app's WCAG compliance by checking contrast, text scaling, and tap target accessibility."
version: 0.0.1
homepage: https://github.com/ChoyaZeno/yuya
repository: https://github.com/ChoyaZeno/yuya

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # Include the AOT compiled snapshot as an asset
  assets:
    - assets/yuya_plugin.aot
